---
on:
    pull_request:

name: Create preview of changes to CI-CD infrastructure

jobs:
    build:
        name: Preview
        runs-on: self-hosted
        steps:
            # ----------------------------------------------
            #           check-out repo, set up node
            # ----------------------------------------------
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: 14.x

            - run: npm install

            # ----------------------------------------------
            #          Run pulumi in preview mode
            # ----------------------------------------------

            - name: Run pulumi preview
              uses: pulumi/actions@v3
              with:
                  command: preview
                  stack-name: maddalab/ci-cd
              env:
                  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

