---
on:
    pull_request:

name: Create preview of changes to CI-CD infrastructure

jobs:
    build:
        name: Preview
        runs-on: self-hosted
        steps:
            # ----------------------------------------------
            #           check-out repo, set up node
            # ----------------------------------------------
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: 14.x

            - run: npm install

            # ----------------------------------------------
            #           configure aws credentials
            # ----------------------------------------------
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            # ----------------------------------------------
            #          Run pulumi in preview mode
            # ----------------------------------------------

            - name: Run pulumi preview
              uses: pulumi/actions@v3
              with:
                  command: preview
                  stack-name: accrue-money/ci-cd
              env:
                  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

